# print help for Just targets
help:
    @just -l

sync-if-needed:
    @if [ ! -d .venv ]; then \
        echo "No .venv found; running 'uv sync'..."; \
        uv sync; \
    fi

detect image: sync-if-needed
    time uv run python whiteboard.py --image {{image}} \
    --ink_frac_max 0.025 \
    --oct_canny1 30 --oct_canny2 90 \
    --oct_ink_dilate 5 \
    --oct_band_inner 0.92 --oct_band_outer 1.10 \
    --oct_scale_min 0.96 --oct_scale_max 1.12 --oct_scale_steps 11 \
    --oct_refine_cy_pix 14 --oct_refine_cy_step 2 \
    --oct_hole_gap_mul 0.70 \
    --icon_alpha 0.65 \
    --icon_pctl_hi 90 \
    --icon_pctl_lo 78 \
    --icon_hyst_iter 3 \
    --icon_center_radius_mul 0.70 \
    --icon_dilate_px 4 \
    --icon_core_radius_mul 0.55 \
    --icon_core_grow_iter 22 \
    --icon_match_min_conf 0.25 \
    --icon_crop_radius_mul 0.70 \
    --icon_library_dir ../devkit/icons/aws \
    --icon_template_size 256 \
    --icon_match_center_radius_mul 0.60 \
    --icon_match_canny1 0 \
    --icon_match_canny2 0 \
    --icon_match_grad_pctl 92

clean:
    rm -rf detections.json debug_patches

test: sync-if-needed
    just detect test_img/3d-dev-kit.webp

sync:
    time uv sync
